# Generated by Django 5.0.7 on 2024-08-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0002_improvepersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.userinfo')),
            ],
            options={
                'verbose_name_plural': '收集信息列表',
            },
        ),
    ]
