# Generated by Django 5.0.7 on 2024-07-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovePersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqqemail', models.CharField(max_length=20)),
                ('uphone', models.CharField(max_length=11)),
                ('ubirthday', models.DateField()),
                ('usex', models.CharField(max_length=10)),
                ('utag', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.userinfo')),
            ],
        ),
    ]
