# Generated by Django 5.0.7 on 2024-08-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynastySort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50, verbose_name='朝代名称')),
            ],
            options={
                'verbose_name_plural': '朝代分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '商品尺码',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, verbose_name='分类名称')),
                ('dynasty_sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.dynastysort', verbose_name='所属朝代')),
            ],
            options={
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimage', models.ImageField(upload_to='static/images/clothing/', verbose_name='商品图片')),
                ('gname', models.CharField(max_length=100, verbose_name='商品名称')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('gspan', models.CharField(max_length=50, verbose_name='标签')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.category', verbose_name='商品所属分类')),
                ('dynasty_sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.dynastysort', verbose_name='商品所属朝代')),
            ],
            options={
                'verbose_name_plural': '商品信息列表',
            },
        ),
        migrations.CreateModel(
            name='GoodsStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstyle', models.ImageField(upload_to='static/images/style/', verbose_name='商品样式图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name_plural': '商品样式',
            },
        ),
    ]
